server:
  port: 8085
logging:
  config: classpath:log4j2.xml
#quartz开关
#quartz:
  #enabled: true
  #profiles: dev
spring:
    application:
      name: promotion  
    datasource:
            driver-class-name: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
            druid:
              url: jdbc:mysql://192.168.1.234:3306/csh?useUnicode=true&characterEncoding=utf8&autoReconnect=true&characterSetResults=utf8
              username: jmm
              password: 51jmm123456
              initial-size: 5
              max-active: 50
              min-idle: 5
              # 配置获取连接等待超时的时间
              max-wait: 60000
              pool-prepared-statements: true
              max-pool-prepared-statement-per-connection-size: 20
              validation-query: SELECT 1
              test-on-borrow: false
              test-on-return: false
              test-while-idle: true
              min-evictable-idle-time-millis: 300000
              time-between-eviction-runs-millis: 300000
              filters: stat
              connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000             
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:9099/eureka/
management:
  security:
    enabled: false              